[phases.setup]
nixPkgs = ["nodejs_20", "yarn", "cairo", "pango", "libjpeg", "giflib", "librsvg", "pixman", "pkg-config"]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = ["export NODE_OPTIONS=--openssl-legacy-provider && yarn build:production"]

[variables]
NODE_OPTIONS = "--openssl-legacy-provider"

[start]
cmd = "node ./dist/api/server.js"
